/**:
  ros__parameters:
    traffic_topic: "/traffic/intruders"
    navigation_topic: "/navigation/state"
    ownship_topic: "/ownship/state"
    use_ownship_fallback: true
    nnet_subdir: "nnets"
    rho_norm_m: 185200.0
    v_norm_mps: 250.0
    timer_period_s: 0.05
